---
name: Setup Node.js

description: Setup Node.js

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
