"aws/management":
  - ".github/workflows/terraform-aws-management.yml"
  - "terraform/aws/environments/management/**"

"aws/sandbox":
  - ".github/workflows/terraform-aws-sandbox.yml"
  - "terraform/aws/environments/sandbox/**"
