"management":
  - ".github/workflows/terraform-aws-management.yml"
  - "terraform/environments/management/**"

"sandbox":
  - ".github/workflows/terraform-aws-sandbox.yml"
  - "terraform/environments/sandbox/**"

"portfolio":
  - ".github/workflows/terraform-aws-portfolio.yml"
  - "terraform/environments/portfolio/**"

"github/blog":
  - ".github/workflows/terraform-aws-blog.yml"
  - "terraform/github/environments/blog/**"
