"aws/management":
  - ".github/workflows/terraform-aws-management.yml"
  - "terraform/aws/environments/management/**"

"aws/sandbox":
  - ".github/workflows/terraform-aws-sandbox.yml"
  - "terraform/aws/environments/sandbox/**"

"aws/portfolio":
  - ".github/workflows/terraform-aws-portfolio.yml"
  - "terraform/aws/environments/portfolio/**"

"github/blog":
  - ".github/workflows/terraform-aws-blog.yml"
  - "terraform/github/environments/blog/**"
