"editorconfig":
  - ".editorconfig"

"document":
  - "**/*.md"
  - "**/*.txt"
  - "**/*.rst"
  - "LICENSE"

"terraform":
  - ".github/actions/terraform**/action.yml"
  - ".github/workflows/terraform**.yml"

"textlint":
  - "**/.textlint*"

"yamllint":
  - "**/.yamllint"

"markdownlint":
  - "**/.markdownlint*.json"

"asdf":
  - "**/.tool-versions"

"actionlint":
  - ".github/workflows/actionlint.yml"

"CODEOWNERS":
  - "CODEOWNERS"

"management":
  - ".github/workflows/terraform-aws-management.yml"
  - "terraform/environments/management/**"

"sandbox":
  - ".github/workflows/terraform-aws-sandbox.yml"
  - "terraform/environments/sandbox/**"

"portfolio":
  - ".github/workflows/terraform-aws-portfolio.yml"
  - "terraform/environments/portfolio/**"
