---
name: set matrix

description: Set matrix

inputs:
  AWS_ENV_NAME:
    description: AWS の環境名
    required: true

outputs:
  matrix:
    description: Terraform の実行対象ディレクトリのリスト
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: pull_request
      if: github.event_name == 'pull_request'
      continue-on-error: true
      run: |
        declare -a deploy_pipelines=($(cat ./.github/workflows/deploy_pipeline/${{ env.AWS_ENV_NAME }}))
        declare -a temp=()
        chmod +x ./.github/scripts/check-for-changes-in-terraform-files.sh

        for pipeline in "${deploy_pipelines[@]}"; do
          ./.github/scripts/check-for-changes-in-terraform-files.sh \
            "terraform/environments/${{ env.AWS_ENV_NAME }}/${pipeline}" \
            "${{ github.head_ref }}"

          # 処理対象のデプロイパイプラインを追加
          [ "$?" == 0 ] && temp+=("$pipeline")
        done

        joined_array=$(printf "\"%s\"," "${temp[@]}")
        echo "joined_array=$(echo "[${joined_array%,}]")" >> $GITHUB_ENV
      shell: bash

    - name: push
      if: github.event_name == 'push'
      run: |
        declare -a deploy_pipelines=($(cat ./.github/workflows/deploy_pipeline/${{ env.AWS_ENV_NAME }}))
        joined_array=$(printf "\"%s\"," "${deploy_pipelines[@]}")
        echo "joined_array=$(echo "[${joined_array%,}]")" >> $GITHUB_ENV
      shell: bash

    - name: make values
      id: set-matrix
      run: |
        echo "matrix=$(echo $joined_array | jq -c)" >> $GITHUB_OUTPUT
      shell: bash
