---
name: RFC 標準的な変更

description: RFC（Request for Change）の標準的な変更

title: "タイトル: "

labels: ["bug", "triage"]

body:
  - type: textarea
    id: raised
    attributes:
      label: RAISED
      description: |
        その変更を**要請**したのは誰？
      placeholder: |
        ex. 架橋太郎
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: REASON
      description: |
        変更する（理由）は？
      placeholder: |
        - ex. 薬歴10項目の機能追加を行うため。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: return
    attributes:
      label: RETURN
      description: |
        変更をすることによって、何を**得られる**のか？
      placeholder: |
        1. ex. AAAAA という課題が解決する。
        2. ex. BBBBB の障害が解消される。
        3. ex. CCCCC のパフォーマンスが向上する。
      value: |
        1.
        2.
        3.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: RISK
      description: |
        変更することによる**危険性・不確実性**は？
      placeholder: |
        1. ex. DDDDD について影響範囲の有無の確認ができない。
        2. ex. 今後のユーザーの増加による負荷を考慮し、監視の設定は追加が必要かもしれない。
        3. ex. 同一の問題が他のリポジトリにもある。
      value: |
        1.
        2.
        3.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: resource
    attributes:
      label: RESOURCE
      description: |
        変更を実施するときに必要になる**リソース**は？
      placeholder: |
        - ex. AWS の EEEEE のテーブルに追加が必要。
        - ex.
        - ex.
      value: |
        -
        -
        -
      render: markdown
    validations:
      required: true

  - type: textarea
    id: responsible
    attributes:
      label: RESPONSIBLE
      description: |
        変更における**責任者**は誰？
      placeholder: |
        - ex. 作業担当者本人
      value: |
        -
        -
        -
      render: markdown
    validations:
      required: true

  - type: textarea
    id: relationship
    attributes:
      label: RELATIONSHIP
      description: |
        他の変更との**関係**は？
      placeholder: |
        - ex. 作業担当者本人
      value: |
        -
        -
        -
      render: markdown
    validations:
      required: true
