---
name: Terraform Plan

description: Terraform Plan

inputs:
  github-token:
    description: サードパーティの Action を実行するための権限を付与するための認証用トークン
    required: true
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  gh-pat:
    description: Personal Access Token for GitHub
    default: ""
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Terraform Validate
      uses: ./.github/actions/terraform-validate
      with:
        github-token: ${{ inputs.github-token }}
        working-directory: ${{ inputs.working-directory }}

    - name: Setup tfcmt
      uses: itkq/actions-tfcmt/setup@main

    - name: Terraform Plan
      id: terraform-plan
      run: |
        TARGET=$(echo ${{ inputs.working-directory }} | sed -e 's|^.*terraform/environments/||' | cut -c 1-36)
        tfcmt --var target:$TARGET plan -patch -- terraform plan -no-color
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TF_VAR_GH_PERSONAL_ACCESS_TOKEN: ${{ inputs.gh-pat }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform Plan (failure) -> Status
      if: steps.terraform-plan.outcome == 'failure'
      run: exit 1
      shell: bash
