---
name: Terraform Graph Beautifier

description: Terraform Graph Beautifier

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: ./.github/actions/setup-go

    - name: Install Terraform Graph Beautifier
      run: |
        go install github.com/pcasteran/terraform-graph-beautifier@latest

        go version
        which go
        which terraform-graph-beautifier
        which terraform
        terraform -v
        terraform-graph-beautifier -v
      shell: bash

    - name: Terraform Graph
      run: |
        # terraform graph | sed -e 's/digraph {/digraph "config1" {/g' | terraform-graph-beautifier \
        terraform graph | terraform-graph-beautifier \
          --output-type=cyto-html \
          > dependency-graph.html
      working-directory: ${{ inputs.working-directory }}
      shell: bash
