---
name: actionlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: actionlint
        uses: rhysd/actionlint@v1.6.23
        with:
          fail_on_error: true
