---
name: pre-commit

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency: secrets-manager

env:
  AWS_ACCOUNT_ID: 107662415716
  ENV_NAME: sandbox
  OIDC_IAM_ROLE: sandbox-private-lab-secrets-manager

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credential
        uses: ./.github/actions/aws-credential
        with:
          oidc-iam-role: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_IAM_ROLE }}

      - name: AWSSecretsManagerから環境変数にシークレットを読み込みます
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        with:
          secrets: |
            sandbox/test
          parse-json: true

      - name: シークレットを取得した後、env変数が設定されているかどうかを確認します
        run: |-
          if [ -z ${MY_SECRET_1+x} ]; then
            echo "MY_SECRET_1 is unset";
          else
            echo "MY_SECRET_1 is set to '$MY_SECRET_1'"
          fi
