---
name: Terraform Plan - Sandbox (difference check)

on:
  schedule:
    # 毎日 7:00(JST) に実行
    - cron: "0 22 * * *"
  workflow_dispatch:

concurrency:
  group: terraform-aws-sandbox-difference-check
  cancel-in-progress: true

jobs:
  terraform-difference-check:
    name: Terraform sandbox
    uses: ./.github/workflows/_terraform-aws-sandbox.yml
    with:
      CHECK_DIFF: "true1"
