---
name: Terraform Validate

description: Terraform Validate

inputs:
  github-token:
    description: サードパーティの Action を実行するための権限を付与
    required: true
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Validate
      run: terraform validate -no-color
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: TFLint
      uses: reviewdog/action-tflint@master
      with:
        github_token: ${{ inputs.github-token }}
        working_directory: ${{ inputs.working-directory }}
        reporter: github-pr-review
        fail_on_error: true
